#!/bin/sh

# I use
# - autoconf (GNU Autoconf) 2.61
# - automake (GNU automake) 1.10
# - ltmain.sh (GNU libtool) 1.5.22-4 (1.1220.2.365 2005/12/18 22:14:06)

set -e
set -x
if test -f Makefile; then
  make distclean
fi
rm -rf *.cache *.m4
rm -f config.guess config.sub depcomp ltmain.sh config.log config.status
(cat m4/*.m4 > acinclude.m4)
autoreconf --verbose --install
